kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-acornbox
  labels:
    app: {{ .Release.Name }}-acornbox
    release: "{{ .Release.Name }}"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
