apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-acornboxworker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-acornboxworker
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-acornboxworker
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: acornboxworker
          image: "acornboxworker:dev"
          imagePullPolicy: Never
          #ports:
          #  - name: http
          #    containerPort: 80
          #    protocol: TCP
          env:
            - name: ConnectionStrings__HangfireConnection
              #value: "Server=acornbox.db; Database=AcornBox; User=sa; Password=Your_password123;"
              value: "Server={{ .Release.Name }}-mssql-linux; Database=AcornBox; User=sa; Password=Your_password123;"
            - name: AcornBoxWebUI
              value: "http://{{ .Release.Name }}-acornboxwebui"
          volumeMounts:
            - name: data
              mountPath: /mnt/share
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-acornbox              
